export const GET_CART_FROM_STORAGE = 'GET_CART_FROM_STORAGE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SUBTRACT_FROM_CART = 'SUBTRACT_FROM_CART';
export const LOCAL_STORAGE_CART_KEY = 'MY_E_COMMERCE_LOCAL_STORAGE_KEY';
